services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: logsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  log-analytics-service:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
      - rabbitmq
